In [17]:
import pandas as pd

df = pd.read_csv('../data/kaggle_dataset.csv')
df.head()

,OyuncuID,OturumSayisi,OyuncuSeviyesi,TotalSatınAlma,Ortalama_Oturum_Suresi,OyunaBaglilik
0,43667,16,43,1,63,Medium
1,31227,10,48,0,99,Medium
2,33899,11,12,0,17,Medium
3,44415,7,44,0,149,Medium
4,30440,10,14,0,127,Medium

In [18]:
df.isnull().sum()

OyuncuID                  0
OturumSayisi              0
OyuncuSeviyesi            0
TotalSatınAlma            0
Ortalama_Oturum_Suresi    0
OyunaBaglilik             0
dtype: int64

In [19]:
df.describe()

,OyuncuID,OturumSayisi,OyuncuSeviyesi,TotalSatınAlma,Ortalama_Oturum_Suresi
count,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000
mean,28993.9289,9.500400,49.452600,0.202400,94.982800
std,11638.7884,5.785667,28.398697,0.401809,49.164573
min,9001.0000,0.000000,1.000000,0.000000,10.000000
25%,18746.0000,4.000000,25.000000,0.000000,52.000000
50%,29024.0000,10.000000,49.000000,0.000000,96.000000
75%,39249.7500,15.000000,74.000000,0.000000,137.000000
max,49019.0000,19.000000,99.000000,1.000000,179.000000