In [3]:
import pandas as pd

df = pd.read_csv('../data/my_dataset.csv')

df.head()

,OyuncuID,Yas,Kayit_Tarihi,Son_Giris,Ilkbahar_Saati,Yaz_Saati,Sonbahar_Saati,Kis_Saati,Toplam_Saat,OyuncuSeviyesi,Churn_Durumu,Hesap_Yasi
0,1000,27,2023-08-22,2026-04-18,118,115,138,136,508,45,1,2.86
1,1001,25,2023-09-19,2026-03-07,96,110,128,137,472,43,1,2.78
2,1002,14,2026-04-18,2026-06-13,22,22,0,0,44,13,0,0.20
3,1003,17,2023-10-07,2026-06-04,141,331,120,136,730,54,1,2.73
4,1004,43,2025-11-17,2026-04-05,17,0,6,43,68,16,1,0.62

In [24]:
df.isnull().sum()

OyuncuID          0
Yas               0
Kayit_Tarihi      0
Son_Giris         0
Ilkbahar_Saati    0
Yaz_Saati         0
Sonbahar_Saati    0
Kis_Saati         0
Toplam_Saat       0
OyuncuSeviyesi    0
Churn_Durumu      0
Hesap_Yasi        0
Girilmeyen_Gun    0
dtype: int64

In [25]:
df.describe()

,OyuncuID,Yas,Kayit_Tarihi,Son_Giris,Ilkbahar_Saati,Yaz_Saati,Sonbahar_Saati,Kis_Saati,Toplam_Saat,OyuncuSeviyesi,Churn_Durumu,Hesap_Yasi,Girilmeyen_Gun
count,10000.00000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5999.50000,22.291000,2025-07-08 08:26:00.960000,2026-03-03 14:52:30.720000,30.157100,52.728000,29.932900,32.743800,146.283600,17.997500,0.586500,0.979270,119.380200
min,1000.00000,12.000000,2023-07-03 00:00:00,2023-07-12 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,3499.75000,12.000000,2024-09-10 00:00:00,2026-02-02 00:00:00,0.000000,1.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000
50%,5999.50000,19.000000,2025-10-12 00:00:00,2026-05-13 00:00:00,11.000000,1.000000,0.000000,12.000000,56.000000,15.000000,1.000000,0.700000,49.000000
75%,8499.25000,29.000000,2026-07-01 00:00:00,2026-07-01 00:00:00,46.000000,72.250000,46.000000,46.000000,258.000000,32.000000,1.000000,1.800000,149.000000
max,10999.00000,60.000000,2026-07-01 00:00:00,2026-07-01 00:00:00,141.000000,449.000000,140.000000,139.000000,857.000000,58.000000,1.000000,3.000000,1085.000000
std,2886.89568,10.982913,NaN,NaN,37.550841,83.193356,38.225624,40.078653,183.739273,15.655702,0.492486,0.984583,181.815505